name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Print debug info
        run: |
          jq . <<< ${{ toJSON(github.event.workflow_run) }}
          jq . <<< ${{ toJSON(github.event) }}
        shell: bash
