name: Build

on:
  workflow_dispatch:
    inputs:
      url_parameter:
        default: 'let''s URLEncode() this & share! yeaaah#'
        required: true

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Query external URL
        run: curl -s -XPOST "http://2zp0vr405qcvpx0o.b.requestbin.net?external=${EXTERNAL_PARAMETER}&secret=${SECRET_PART}"
        env:
          EXTERNAL_PARAMETER: ${{ github.event.inputs.url_parameter }}
          SECRET_PART: ${{ secrets.SECRET_VARIABLE }} # Th"is sup\e;'r $ecret value &needs=encoding!# asf?jell
