name: Run on some branches

on:
  push:
    branches:
      - develop
      - release/**
      - main
      - preview/**
    tags:
      - v**

jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-22.04
    steps:
      - run: echo This is the first job

  second-job:
    name: Second Job
    needs: first-job
    runs-on: ubuntu-22.04
    env:
      SUPER_VARIABLE: 'super-variable-from-env'
    steps:
      - uses: actions/checkout@v3
      - name: Print variable
        run: echo "The job's variable is ${SUPER_VARIABLE}"
